// @flow

import React from 'react'

// to update site favicons easily, use http://www.favicon-generator.org/
// and upload the entire folder to wordpress

export default function (images: Object) {
  return [
    <link
      href={images['apple-icon-57x57']}
      key='apple-icon-57x57'
      rel='apple-touch-icon'
      sizes='57x57'
    />,
    <link
      href={images['apple-icon-60x60']}
      key='apple-icon-60x60'
      rel='apple-touch-icon'
      sizes='60x60'
    />,
    <link
      href={images['apple-icon-72x72']}
      key='apple-icon-72x72'
      rel='apple-touch-icon'
      sizes='72x72'
    />,
    <link
      href={images['apple-icon-76x76']}
      key='apple-icon-76x76'
      rel='apple-touch-icon'
      sizes='76x76'
    />,
    <link
      href={images['apple-icon-114x114']}
      key='apple-icon-114x114'
      rel='apple-touch-icon'
      sizes='114x114'
    />,
    <link
      href={images['apple-icon-120x120']}
      key='apple-icon-120x120'
      rel='apple-touch-icon'
      sizes='120x120'
    />,
    <link
      href={images['apple-icon-144x144']}
      key='apple-icon-144x144'
      rel='apple-touch-icon'
      sizes='144x144'
    />,
    <link
      href={images['apple-icon-152x152']}
      key='apple-icon-152x152'
      rel='apple-touch-icon'
      sizes='152x152'
    />,
    <link
      href={images['apple-icon-180x180']}
      key='apple-icon-180x180'
      rel='apple-touch-icon'
      sizes='180x180'
    />,
    <link
      href={images['android-icon-192x192']}
      key='android-icon-192x192'
      rel='icon'
      sizes='192x192'
      type='image/png'
    />,
    <link
      href={images['favicon-32x32']}
      key='favicon-32x32'
      rel='icon'
      sizes='32x32'
      type='image/png'
    />,
    <link
      href={images['favicon-96x96']}
      key='favicon-96x96'
      rel='icon'
      sizes='96x96'
      type='image/png'
    />,
    <link
      href={images['favicon-16x16']}
      key='favicon-16x16'
      rel='icon'
      sizes='16x16'
      type='image/png'
    />,
    <meta
      content={images['ms-icon-144x144']}
      key='msapplication-TileImage'
      name='msapplication-TileImage'
    />,
    <meta
      content='#ffffff'
      key='msapplication-TileColor'
      name='msapplication-TileColor'
    />,
    <meta
      content='#ffffff'
      key='theme-color'
      name='theme-color'
    />
  ]
}
