// flow-typed signature: 9dd21592805ce0b239fc52e68f89714c
// flow-typed version: <<STUB>>/import-glob-loader_v^1.1.0/flow_v0.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'import-glob-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'import-glob-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'import-glob-loader/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'import-glob-loader/index' {
  declare module.exports: $Exports<'import-glob-loader'>;
}
declare module 'import-glob-loader/index.js' {
  declare module.exports: $Exports<'import-glob-loader'>;
}
declare module 'import-glob-loader/src/index.js' {
  declare module.exports: $Exports<'import-glob-loader/src/index'>;
}
