// flow-typed signature: c2878ba27fba672f06c44d3c9694f962
// flow-typed version: <<STUB>>/js-cookie_v^2.1.4/flow_v0.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-cookie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-cookie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-cookie/Gruntfile' {
  declare module.exports: any;
}

declare module 'js-cookie/src/js.cookie' {
  declare module.exports: any;
}

declare module 'js-cookie/test/amd-config' {
  declare module.exports: any;
}

declare module 'js-cookie/test/amd' {
  declare module.exports: any;
}

declare module 'js-cookie/test/encoding' {
  declare module.exports: any;
}

declare module 'js-cookie/test/environment-with-amd-and-umd' {
  declare module.exports: any;
}

declare module 'js-cookie/test/node' {
  declare module.exports: any;
}

declare module 'js-cookie/test/polyfill' {
  declare module.exports: any;
}

declare module 'js-cookie/test/tests' {
  declare module.exports: any;
}

declare module 'js-cookie/test/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-cookie/Gruntfile.js' {
  declare module.exports: $Exports<'js-cookie/Gruntfile'>;
}
declare module 'js-cookie/src/js.cookie.js' {
  declare module.exports: $Exports<'js-cookie/src/js.cookie'>;
}
declare module 'js-cookie/test/amd-config.js' {
  declare module.exports: $Exports<'js-cookie/test/amd-config'>;
}
declare module 'js-cookie/test/amd.js' {
  declare module.exports: $Exports<'js-cookie/test/amd'>;
}
declare module 'js-cookie/test/encoding.js' {
  declare module.exports: $Exports<'js-cookie/test/encoding'>;
}
declare module 'js-cookie/test/environment-with-amd-and-umd.js' {
  declare module.exports: $Exports<'js-cookie/test/environment-with-amd-and-umd'>;
}
declare module 'js-cookie/test/node.js' {
  declare module.exports: $Exports<'js-cookie/test/node'>;
}
declare module 'js-cookie/test/polyfill.js' {
  declare module.exports: $Exports<'js-cookie/test/polyfill'>;
}
declare module 'js-cookie/test/tests.js' {
  declare module.exports: $Exports<'js-cookie/test/tests'>;
}
declare module 'js-cookie/test/utils.js' {
  declare module.exports: $Exports<'js-cookie/test/utils'>;
}
