// flow-typed signature: 7572fc2b8fab9bae6c13082bac7c50c5
// flow-typed version: <<STUB>>/react-icon_vx.x.x/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-icon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-icon' {
  declare module.exports: any;
}
